<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use yii\helpers\StringHelper;

/**
* @var yii\web\View $this
* @var app\models\Propuesta $model
* @var yii\widgets\ActiveForm $form
*/

?>

<div class="propuesta-form">

    <?php $form = ActiveForm::begin([
    'id' => 'Propuesta',
    'layout' => 'horizontal',
    'enableClientValidation' => true,
    'errorSummaryCssClass' => 'error-summary alert alert-danger',
    'fieldConfig' => [
             'template' => "{label}\n{beginWrapper}\n{input}\n{hint}\n{error}\n{endWrapper}",
             'horizontalCssClasses' => [
                 'label' => 'col-sm-2',
                 #'offset' => 'col-sm-offset-4',
                 'wrapper' => 'col-sm-8',
                 'error' => '',
                 'hint' => '',
             ],
         ],
    ]
    );
    ?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>
            

<!-- attribute anyo -->
			<?= $form->field($model, 'anyo')->textInput() ?>

<!-- attribute user_id -->
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'user_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\User::find()->all(), 'id', 'id'),
    [
        'prompt' => Yii::t('cruds', 'Select'),
        'disabled' => (isset($relAttributes) && isset($relAttributes['user_id'])),
    ]
); ?>

<!-- attribute orientacion_id -->
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'orientacion_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\Orientacion::find()->all(), 'id', 'id'),
    [
        'prompt' => Yii::t('cruds', 'Select'),
        'disabled' => (isset($relAttributes) && isset($relAttributes['orientacion_id'])),
    ]
); ?>

<!-- attribute creditos -->
			<?= $form->field($model, 'creditos')->textInput() ?>

<!-- attribute duracion -->
			<?= $form->field($model, 'duracion')->textInput() ?>

<!-- attribute modalidad_id -->
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'modalidad_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\Modalidad::find()->all(), 'id', 'id'),
    [
        'prompt' => Yii::t('cruds', 'Select'),
        'disabled' => (isset($relAttributes) && isset($relAttributes['modalidad_id'])),
    ]
); ?>

<!-- attribute plazas -->
			<?= $form->field($model, 'plazas')->textInput() ?>

<!-- attribute tipo_estudio_id -->
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'tipo_estudio_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\TipoEstudio::find()->all(), 'id', 'id'),
    [
        'prompt' => Yii::t('cruds', 'Select'),
        'disabled' => (isset($relAttributes) && isset($relAttributes['tipo_estudio_id'])),
    ]
); ?>

<!-- attribute estado_id -->
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'estado_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\Estado::find()->all(), 'id', 'id'),
    [
        'prompt' => Yii::t('cruds', 'Select'),
        'disabled' => (isset($relAttributes) && isset($relAttributes['estado_id'])),
    ]
); ?>

<!-- attribute creditos_practicas -->
			<?= $form->field($model, 'creditos_practicas')->textInput(['maxlength' => true]) ?>

<!-- attribute log -->
			<?= $form->field($model, 'log')->textarea(['rows' => 6]) ?>

<!-- attribute denominacion -->
			<?= $form->field($model, 'denominacion')->textInput(['maxlength' => true]) ?>

<!-- attribute memoria_verificacion -->
			<?= $form->field($model, 'memoria_verificacion')->textInput(['maxlength' => true]) ?>

<!-- attribute memoria_economica -->
			<?= $form->field($model, 'memoria_economica')->textInput(['maxlength' => true]) ?>
        </p>
        <?php $this->endBlock(); ?>
        
        <?=
    Tabs::widget(
                 [
                    'encodeLabels' => false,
                    'items' => [ 
                        [
    'label'   => Yii::t('models', 'Propuesta'),
    'content' => $this->blocks['main'],
    'active'  => true,
],
                    ]
                 ]
    );
    ?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?= Html::submitButton(
        '<span class="glyphicon glyphicon-check"></span> ' .
        ($model->isNewRecord ? Yii::t('cruds', 'Create') : Yii::t('cruds', 'Save')),
        [
        'id' => 'save-' . $model->formName(),
        'class' => 'btn btn-success'
        ]
        );
        ?>

        <?php ActiveForm::end(); ?>

    </div>

</div>

