<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Aviso legal' => '',
    'Ayuda' => '',
    'Cerrar sesión' => '',
    'Condiciones generales de uso' => '',
    'Contacte con nosotros si piensa que es un error del servidor. Gracias.' => '',
    'Enlaces' => '',
    'Gestión' => '',
    'Iniciar sesión' => '',
    'No tiene permisos para acceder a esta página. 😨' => '',
    'Número de Identificación Personal' => '',
    'Off' => '',
    'On' => '',
    'Política de privacidad' => '',
    'Propuestas' => '',
    'Propuestas de nuevas titulaciones' => '',
    'Se produjo el error superior mientras el servidor web procesaba su petición.' => '',
    'Servicio de Informática y Comunicaciones de la Universidad de Zaragoza' => '',
    'Universidad de Zaragoza' => '',
    'Área de Aplicaciones. Servicio de Informática y Comunicaciones de la Universidad de Zaragoza.' => '',
    'Could not bind to the LDAP server.' => 'No fue posible conectarse al servidor LDAP.',
    'The provided LDAP parameters are syntactically wrong.' => 'Los parámetros de LDAP proporcionados no son sintácticamente correctos.',
    'Unable to search LDAP server' => 'No fue posible buscar en el servidor LDAP.',
    'You are not allowed to {0} record #{1}' => 'No está autorizado para {0} el registro nº {1}',
];
