<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "bloque".
 *
 * @property integer $id
 * @property integer $pregunta_id
 * @property string $titulo
 * @property string $descripcion
 * @property string $porcentaje
 * @property integer $tiene_puntuacion_interna
 *
 * @property \app\models\Pregunta $pregunta
 * @property \app\models\Valoracion[] $valoracions
 * @property string $aliasModel
 */
abstract class Bloque extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'bloque';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['pregunta_id', 'tiene_puntuacion_interna'], 'integer'],
            [['descripcion'], 'string'],
            [['porcentaje'], 'number'],
            [['titulo'], 'string', 'max' => 100],
            [['pregunta_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Pregunta::className(), 'targetAttribute' => ['pregunta_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'pregunta_id' => Yii::t('models', 'Pregunta ID'),
            'titulo' => Yii::t('models', 'Titulo'),
            'descripcion' => Yii::t('models', 'Descripcion'),
            'porcentaje' => Yii::t('models', 'Porcentaje'),
            'tiene_puntuacion_interna' => Yii::t('models', 'Tiene Puntuacion Interna'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPregunta()
    {
        return $this->hasOne(\app\models\Pregunta::className(), ['id' => 'pregunta_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getValoracions()
    {
        return $this->hasMany(\app\models\Valoracion::className(), ['bloque_id' => 'id']);
    }




}
