<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "convenio_intercambios".
 *
 * @property integer $id
 * @property integer $propuesta_id
 * @property string $nombre_entidad
 * @property string $documento
 *
 * @property \app\models\Propuesta $propuesta
 * @property string $aliasModel
 */
abstract class ConvenioIntercambios extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'convenio_intercambios';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['propuesta_id'], 'required'],
            [['propuesta_id'], 'integer'],
            [['nombre_entidad', 'documento'], 'string', 'max' => 255],
            [['propuesta_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Propuesta::className(), 'targetAttribute' => ['propuesta_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'propuesta_id' => Yii::t('models', 'Propuesta ID'),
            'nombre_entidad' => Yii::t('models', 'Nombre Entidad'),
            'documento' => Yii::t('models', 'Documento'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPropuesta()
    {
        return $this->hasOne(\app\models\Propuesta::className(), ['id' => 'propuesta_id']);
    }




}
