<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "macroarea".
 *
 * @property integer $id
 * @property string $id_nk
 * @property string $nombre
 *
 * @property \app\models\PropuestaMacroarea[] $propuestaMacroareas
 * @property string $aliasModel
 */
abstract class Macroarea extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'macroarea';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_nk'], 'string', 'max' => 1],
            [['nombre'], 'string', 'max' => 50]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'id_nk' => Yii::t('models', 'Id Nk'),
            'nombre' => Yii::t('models', 'Nombre'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPropuestaMacroareas()
    {
        return $this->hasMany(\app\models\PropuestaMacroarea::className(), ['macroarea_id' => 'id']);
    }




}
