<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "propuesta".
 *
 * @property integer $id
 * @property integer $anyo
 * @property integer $user_id
 * @property string $denominacion
 * @property integer $orientacion_id
 * @property integer $creditos
 * @property integer $duracion
 * @property integer $modalidad_id
 * @property integer $plazas
 * @property string $creditos_practicas
 * @property integer $tipo_estudio_id
 * @property integer $estado_id
 * @property string $log
 *
 * @property \app\models\Estado $estado
 * @property \app\models\Modalidad $modalidad
 * @property \app\models\Orientacion $orientacion
 * @property \app\models\TipoEstudio $tipoEstudio
 * @property \app\models\User $user
 * @property \app\models\PropuestaCentro[] $propuestaCentros
 * @property \app\models\PropuestaDoctorado[] $propuestaDoctorados
 * @property \app\models\PropuestaEvaluador[] $propuestaEvaluadors
 * @property \app\models\PropuestaGrupoInves[] $propuestaGrupoInves
 * @property \app\models\PropuestaMacroarea[] $propuestaMacroareas
 * @property \app\models\PropuestaTitulacion[] $propuestaTitulacions
 * @property \app\models\Respuesta[] $respuestas
 * @property \app\models\Valoracion[] $valoracions
 * @property string $aliasModel
 */
abstract class Propuesta extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'propuesta';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['anyo', 'user_id', 'orientacion_id', 'creditos', 'duracion', 'modalidad_id', 'plazas', 'tipo_estudio_id', 'estado_id'], 'integer'],
            [['creditos_practicas'], 'number'],
            [['log'], 'string'],
            [['denominacion'], 'string', 'max' => 250],
            [['estado_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Estado::className(), 'targetAttribute' => ['estado_id' => 'id']],
            [['modalidad_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Modalidad::className(), 'targetAttribute' => ['modalidad_id' => 'id']],
            [['orientacion_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Orientacion::className(), 'targetAttribute' => ['orientacion_id' => 'id']],
            [['tipo_estudio_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\TipoEstudio::className(), 'targetAttribute' => ['tipo_estudio_id' => 'id']],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::className(), 'targetAttribute' => ['user_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'anyo' => Yii::t('models', 'Anyo'),
            'user_id' => Yii::t('models', 'User ID'),
            'denominacion' => Yii::t('models', 'Denominacion'),
            'orientacion_id' => Yii::t('models', 'Orientacion ID'),
            'creditos' => Yii::t('models', 'Creditos'),
            'duracion' => Yii::t('models', 'Duracion'),
            'modalidad_id' => Yii::t('models', 'Modalidad ID'),
            'plazas' => Yii::t('models', 'Plazas'),
            'creditos_practicas' => Yii::t('models', 'Creditos Practicas'),
            'tipo_estudio_id' => Yii::t('models', 'Tipo Estudio ID'),
            'estado_id' => Yii::t('models', 'Estado ID'),
            'log' => Yii::t('models', 'Log'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEstado()
    {
        return $this->hasOne(\app\models\Estado::className(), ['id' => 'estado_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getModalidad()
    {
        return $this->hasOne(\app\models\Modalidad::className(), ['id' => 'modalidad_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOrientacion()
    {
        return $this->hasOne(\app\models\Orientacion::className(), ['id' => 'orientacion_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTipoEstudio()
    {
        return $this->hasOne(\app\models\TipoEstudio::className(), ['id' => 'tipo_estudio_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\app\models\User::className(), ['id' => 'user_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPropuestaCentros()
    {
        return $this->hasMany(\app\models\PropuestaCentro::className(), ['propuesta_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPropuestaDoctorados()
    {
        return $this->hasMany(\app\models\PropuestaDoctorado::className(), ['propuesta_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPropuestaEvaluadors()
    {
        return $this->hasMany(\app\models\PropuestaEvaluador::className(), ['propuesta_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPropuestaGrupoInves()
    {
        return $this->hasMany(\app\models\PropuestaGrupoInves::className(), ['propuesta_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPropuestaMacroareas()
    {
        return $this->hasMany(\app\models\PropuestaMacroarea::className(), ['propuesta_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPropuestaTitulacions()
    {
        return $this->hasMany(\app\models\PropuestaTitulacion::className(), ['propuesta_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRespuestas()
    {
        return $this->hasMany(\app\models\Respuesta::className(), ['propuesta_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getValoracions()
    {
        return $this->hasMany(\app\models\Valoracion::className(), ['propuesta_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\PropuestaQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\PropuestaQuery(get_called_class());
    }


}
