<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "respuesta".
 *
 * @property integer $id
 * @property integer $propuesta_id
 * @property integer $pregunta_id
 * @property string $valor
 *
 * @property \app\models\Pregunta $pregunta
 * @property \app\models\Propuesta $propuesta
 * @property string $aliasModel
 */
abstract class Respuesta extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'respuesta';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['propuesta_id', 'pregunta_id'], 'integer'],
            [['valor'], 'string'],
            [['pregunta_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Pregunta::className(), 'targetAttribute' => ['pregunta_id' => 'id']],
            [['propuesta_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Propuesta::className(), 'targetAttribute' => ['propuesta_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'propuesta_id' => Yii::t('models', 'Propuesta ID'),
            'pregunta_id' => Yii::t('models', 'Pregunta ID'),
            'valor' => Yii::t('models', 'Valor'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPregunta()
    {
        return $this->hasOne(\app\models\Pregunta::className(), ['id' => 'pregunta_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPropuesta()
    {
        return $this->hasOne(\app\models\Propuesta::className(), ['id' => 'propuesta_id']);
    }




}
