<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '%s ya no tiene el rol «%s».' => '',
    'Aprobar la propuesta para que sea valorada externamente.' => '',
    'Añadir' => '',
    'Añadir usuario al rol «%s»' => '',
    'Bloque' => '',
    'Devolver al evaluador' => '',
    'Devolver la propuesta al proponente, si ésta tiene defectos que pueden ser subsanados.' => '',
    'Editar los evaluadores' => '',
    'El proponente podrá hacer correcciones y volver a presentarla.' => '',
    'El proponente podrá hacer modificaciones y volver a presentarla.' => '',
    'El rol «%s» no existe. 😨' => '',
    'El usuario «%d» ya tenía el rol «%s». 😨' => '',
    'Esta página muestra una propuesta presentada.  Aquí puede:' => '',
    'Evaluador' => '',
    'Introduzca un NIP' => '',
    'La propuesta quedará archivada pasa su consulta.' => '',
    'Las propuestas desestimadas quedan archivadas.' => '',
    'Media' => '',
    'No se ha encontrado el NIP «%d» en Gestión de Identidades. 😨' => '',
    'Puntuaciones' => '',
    'Puntuación' => '',
    'Puntuación final' => '',
    'Quitar este evaluador de esta propuesta' => '',
    'Quitar este evaluador de esta propuestas' => '',
    'Quitar rol al usuario' => '',
    'Rechazar la propuesta, si ésta carece de interés y no merece ser evaluada.' => '',
    'Resumen de valoraciones' => '',
    'Se ha quitado al evaluador %s de esta propuesta.' => '',
    'Se ha vuelto a abrir la evaluación de la propuesta «%s» por el evaluador «%s».' => '',
    'Todos' => '',
    '¿Seguro que desea aprobar esta propuesta?' => '',
    '¿Seguro que desea desestimar esta propuesta?' => '',
    '¿Seguro que desea devolver esta propuesta al proponente?' => '',
    '¿Seguro que desea eliminar este evaluador de esta propuesta?' => '',
    '¿Seguro que desea eliminar este usuario del rol?' => '',
    '¿Seguro que desea volver a abrir esta evaluación?' => '',
];
