<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '(no definido)' => '',
    'Aprobación interna de la propuesta' => '',
    'Aprobar internamente' => '',
    'Añadir centro' => '',
    'Añadir grupo de investigación' => '',
    'Añadir programa de doctorado' => '',
    'Añadir titulación' => '',
    'Borrar' => '',
    'Cambios guardados con éxito.' => '',
    'Cancelar' => '',
    'Centro gestor' => '',
    'Centro(s)' => '',
    'Continuar' => '',
    'Correo del responsable' => '',
    'Creación de la propuesta' => '',
    'Crear una nueva propuesta' => '',
    'Crear usuario' => '',
    'Datos identificativos del máster' => '',
    'Devolver al proponente' => '',
    'Editar' => '',
    'Editar datos identificativos' => '',
    'Editar respuesta' => '',
    'En caso de haber más de uno, el primero será el centro gestor.' => '',
    'Esta propuesta no está en estado «Presentada». 😨' => '',
    'Esta propuesta ya estaba presentada. 😨' => '',
    'Esta propuesta ya ha sido presentada, por lo que ya no se puede editar. 😨' => '',
    'Estado' => '',
    'Grupos de investigación reconocidos por el Gobierno de Aragón que apoyan la propuesta' => '',
    'Guardar' => '',
    'La propuesta cumple los criterios.
Aprobarla para su evaluación externa.' => '',
    'La propuesta está acabada. Presentarla.' => '',
    'La propuesta ha sido aprobada internamente.
Si lo desea, puede enviar un mensaje de correo electrónico al autor de la propuesta: ' => '',
    'La propuesta ha sido presentada correctamente.
En breve debería recibir un correo electrónico de confirmación.
No obstante, si lo desea puede imprimir está página a modo de resguardo.' => '',
    'La propuesta ha sido rechazada internamente.
Por favor, <strong>informe al autor de la propuesta</strong> enviándole un mensaje de correo electrónico: ' => '',
    'La propuesta no cumple los requisitos.
Volverla a poner en estado borrador para su corrección.' => '',
    'Macroárea(s)' => '',
    'Modalidad de impartición' => '',
    'Máximo: %d caracteres, aprox. %d palabras' => '',
    'No se ha encontrado esa propuesta.  ☹' => '',
    'Nombre de usuario con el que iniciar sesión' => '',
    'Nombre del responsable' => '',
    'Nombre y apellidos del usuario' => '',
    'Nueva propuesta' => '',
    'Orientación' => '',
    'Presentación de la propuesta' => '',
    'Presentar la propuesta' => '',
    'Presentar la propuesta para su evaluación.
Ya no se podrán hacer más modificaciones.' => '',
    'Programa de doctorado a los que podría dar acceso' => '',
    'Programas de doctorado a los que podría dar acceso' => '',
    'Propuesta aprobada internamente' => '',
    'Propuesta guardada con éxito.' => '',
    'Propuesta presentada' => '',
    'Propuesta rechazada internamente' => '',
    'Propuestas aprobadas externamente' => '',
    'Propuestas aprobadas internamente' => '',
    'Propuestas de <strong>másteres</strong><br>de referencia' => '',
    'Propuestas en borrador' => '',
    'Propuestas presentadas' => '',
    'Propuestas rechazadas externamente' => '',
    'Rechazo interno de la propuesta' => '',
    'Reemplazar documento' => '',
    'Se ha creado el usuario «%s».  Por favor, infórmele de su nombre de usuario y contraseña.
Al tratarse de un usuario externo, para iniciar sesión deberá usar la dirección
%s' => '',
    'Seleccione la modalidad' => '',
    'Seleccione la orientación' => '',
    'Titulaciones a las que va dirigido' => '',
    'Usuario responsable' => '',
    'Usuarios del rol «%s»' => '',
    'Valoradores' => '',
    '¡No puede asignar el rol de administrador!' => '',
    '¿Presentar la propuesta?' => '',
    '¿Seguro que ha finalizado y desea presentar la propuesta de «%s»?<br>Una vez la haya presentado ya no podrá modificarla.' => '',
];
